In [1]:
import pandas as pd                    

schedule_data = pd.read_csv(r'C:\Users\User\Desktop\Class Stuff\Python Practice\Schedule\tests\data\schedule_example.csv')
schedule_data = schedule_data.drop(columns=['Unnamed: 0'])
schedule_data

        Week     RA       Role       Day       Preference
0     Week 1  Anon2    Primary    Sunday      (requested)
1     Week 1  Anon6  Secondary    Sunday      (requested)
2     Week 1  Anon5    Primary    Monday      (requested)
3     Week 1  Anon2  Secondary    Monday      (requested)
4     Week 1  Anon4    Primary   Tuesday      (requested)
..       ...    ...        ...       ...              ...
149  Week 11  Anon4  Secondary  Thursday      (requested)
150  Week 11  Anon4    Primary    Friday      (requested)
151  Week 11  Anon1  Secondary    Friday      (requested)
152  Week 11  Anon2    Primary  Saturday  (not requested)
153  Week 11  Anon4  Secondary  Saturday      (requested)

[154 rows x 5 columns]

In [2]:
# First, split the data into primary and secondary shifts
primary_shifts = schedule_data[schedule_data['Role'] == 'Primary']
secondary_shifts = schedule_data[schedule_data['Role'] == 'Secondary']

# Then rename the columns, keep only necessary data, and reset the index for the merge of primary shift data
rename_primary = primary_shifts.rename(columns={'RA':'Primary RA', 'Preference': 'Primary Preference'})
primary_shifts_merge = rename_primary[['Week', 'Day', 'Primary RA', 'Primary Preference']].reset_index()

# Repeat for secondary shifts # NOTE : only need Name and preference, We're using indexes to merge
rename_secondary = secondary_shifts.rename(columns={'RA':'Secondary RA', 'Preference': 'Secondary Preference'})
secondary_shifts_merge = rename_secondary[['Secondary RA', 'Secondary Preference']].reset_index()

# Merge the primary and secondary shift dataframes
schedule = pd.merge(left=primary_shifts_merge, right=secondary_shifts_merge, left_index=True, right_index=True)
schedule.drop(columns=['index_x', 'index_y'], inplace=True)
schedule

,Week,Day,Primary RA,Primary Preference,Secondary RA,Secondary Preference
0,Week 1,Sunday,Anon2,(requested),Anon6,(requested)
1,Week 1,Monday,Anon5,(requested),Anon2,(requested)
2,Week 1,Tuesday,Anon4,(requested),Anon2,(requested)
3,Week 1,Wednesday,Anon5,(requested),Anon1,(requested)
4,Week 1,Thursday,Eli,(requested),Anon4,(requested)
...,...,...,...,...,...,...
72,Week 11,Tuesday,Anon4,(requested),Anon6,(requested)
73,Week 11,Wednesday,Eli,(requested),Anon5,(requested)
74,Week 11,Thursday,Anon1,(requested),Anon4,(requested)
75,Week 11,Friday,Anon4,(requested),Anon1,(requested)
76,Week 11,Saturday,Anon2,(not requested),Anon4,(requested)